import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { POSTS } from './scripts/blog-posts.mjs'

// Each blog post is its own static page at blog/<slug>/index.html (generated by
// scripts/gen-blog.mjs on predev/prebuild). Register them as inputs so Vite injects
// the hashed CSS and substitutes %VITE_SITE_URL%, same as the other MPA entries.
const blogPosts = Object.fromEntries(
  POSTS.map((p) => [`blog-${p.slug}`, `blog/${p.slug}/index.html`]),
)

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    // multi-page: projects/index.html builds to dist/projects/index.html, which
    // Apache serves at /projects/ with no rewrite rules and no client router
    rollupOptions: {
      input: {
        main: "index.html",
        projects: "projects/index.html",
        about: "about/index.html",
        blog: "blog/index.html",
        ...blogPosts,
      },
    },
  },
})
