/**
 * Downloads the three webfont families into public/fonts/ and regenerates
 * src/styles/fonts.css, so nothing is fetched from fonts.googleapis.com at runtime.
 *
 * Only latin + latin-ext are kept — everything English and Slovak need. Google
 * also serves cyrillic, greek and vietnamese, which this site never renders.
 *
 * Run by hand after changing FAMILIES; not part of dev/build (the files are
 * committed). All three families are SIL OFL 1.1 — see public/fonts/LICENSE.txt.
 *
 *   node scripts/fonts.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const outDir = resolve(root, "public", "fonts");

// a desktop UA is what makes the API hand back woff2 rather than ttf
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const FAMILIES = [
  "Inter:wght@400..600",
  "JetBrains+Mono:wght@400..600",
  "Space+Grotesk:wght@300..700",
];
const KEEP = new Set(["latin", "latin-ext"]);

const cssUrl = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join("&")}&display=swap`;

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

async function fetchText(url) {
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} for ${url}`);
  return r.text();
}

mkdirSync(outDir, { recursive: true });
const css = await fetchText(cssUrl);

// every @font-face is preceded by a /* subset */ comment
const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
const faces = [];
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = block.match(/font-family:\s*'([^']+)'/)[1];
  const weight = block.match(/font-weight:\s*([^;]+);/)[1].trim();
  const range = block.match(/unicode-range:\s*([^;]+);/)[1].trim();
  const url = block.match(/url\((https:\/\/[^)]+)\)/)[1];

  const file = `${slug(family)}-${subset}.woff2`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(resolve(outDir, file), buf);
  bytes += buf.length;
  console.log(`  ${file.padEnd(32)} ${weight.padEnd(10)} ${(buf.length / 1024).toFixed(1)} kB`);

  faces.push(`@font-face {
  font-family: "${family}";
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url("/fonts/${file}") format("woff2");
  unicode-range: ${range};
}`);
}

const header = `/*
 * Self-hosted webfonts. Replaces the render-blocking fonts.googleapis.com link
 * that used to hold up first paint on every page navigation.
 *
 * Generated by scripts/fonts.mjs — edit that, not this file. Only latin +
 * latin-ext are shipped: everything English and Slovak need, without the
 * cyrillic/greek/vietnamese subsets Google serves by default.
 *
 * All three families are SIL Open Font License 1.1 — see public/fonts/LICENSE.txt.
 */

`;
writeFileSync(resolve(root, "src", "styles", "fonts.css"), header + faces.join("\n\n") + "\n");
console.log(`[fonts] ${faces.length} files, ${(bytes / 1024).toFixed(1)} kB total → public/fonts/`);
