/**
 * Generates public/robots.txt, public/sitemap.xml and public/llms.txt from the
 * single VITE_SITE_URL value (see .env). Runs automatically before `dev` and
 * `build` (see package.json), so these files always match the configured domain.
 *
 *   node scripts/seo.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const pub = resolve(root, "public");

// ── resolve the domain (env → .env file → default), no trailing slash ──────────
function readEnvFile() {
  const p = resolve(root, ".env");
  if (!existsSync(p)) return {};
  const out = {};
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}
const env = readEnvFile();
const SITE_URL = (process.env.VITE_SITE_URL || env.VITE_SITE_URL || "https://www.etereo.sk").replace(/\/+$/, "");
const today = new Date().toISOString().slice(0, 10);

if (!existsSync(pub)) mkdirSync(pub, { recursive: true });

// ── robots.txt ─────────────────────────────────────────────────────────────────
// We WELCOME AI crawlers: the site should be quotable by ChatGPT, Claude,
// Perplexity, Google AI, Apple, etc. Explicit Allow blocks signal that intent.
const AI_AGENTS = [
  "GPTBot", "OAI-SearchBot", "ChatGPT-User",          // OpenAI
  "ClaudeBot", "Claude-SearchBot", "Claude-User", "anthropic-ai", // Anthropic
  "PerplexityBot", "Perplexity-User",                  // Perplexity
  "Google-Extended",                                   // Google AI
  "Applebot", "Applebot-Extended",                     // Apple
  "Amazonbot",                                         // Amazon
  "meta-externalagent",                                // Meta
  "CCBot",                                             // Common Crawl
  "cohere-ai",                                         // Cohere
  "DuckAssistBot",                                     // DuckDuckGo
  "MistralAI-User",                                    // Mistral
];

const robots = `# robots.txt — ${SITE_URL}
# Generated by scripts/seo.mjs. Edit .env (VITE_SITE_URL), not this file.

# Search + AI crawlers are welcome to index and cite this site.
User-agent: *
Allow: /

${AI_AGENTS.map((a) => `User-agent: ${a}\nAllow: /`).join("\n\n")}

Sitemap: ${SITE_URL}/sitemap.xml
`;
writeFileSync(resolve(pub, "robots.txt"), robots);

// ── sitemap.xml (single-page site with EN + SK variants) ─────────────────────────
const pages = [
  { loc: `${SITE_URL}/`, priority: "1.0" },
  { loc: `${SITE_URL}/?lang=sk`, priority: "0.9" },
];
const alt = `    <xhtml:link rel="alternate" hreflang="en" href="${SITE_URL}/"/>
    <xhtml:link rel="alternate" hreflang="sk" href="${SITE_URL}/?lang=sk"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE_URL}/"/>`;
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${pages
  .map(
    (p) => `  <url>
    <loc>${p.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${p.priority}</priority>
${alt}
  </url>`
  )
  .join("\n")}
</urlset>
`;
writeFileSync(resolve(pub, "sitemap.xml"), sitemap);

// ── llms.txt (the "AI SEO" file: a clean, quotable brief for LLMs) ───────────────
const llms = `# ETEREO

> ETEREO (legal name ETEREO s.r.o.) is a Slovakia-based software house that rebuilds the systems established companies already run on. Founded in 2026 by Patrik Klimko and Matej Kučera, ETEREO delivers legacy modernisation, custom software, SaaS products, and mobile & web engineering with one accountable team — strategy, architecture and delivery together. Remote-first, based in Bratislava, working across Slovakia, Central Europe and internationally, in English and Slovak.

## What ETEREO does

- **Digital transformation** — legacy platforms replatformed in slices, with the business running the whole way through (no big-bang cutovers).
- **Custom software** — line-of-business systems built around how an operation actually works.
- **SaaS products** — multi-tenant products from zero: billing, entitlements, admin, telemetry.
- **Mobile engineering** — iOS, Android and cross-platform apps with offline behaviour and release automation.
- **Web platforms** — sites, portals and commerce fronts engineered for performance and accessibility (WCAG 2.2).
- **Cloud & platform** — infrastructure as code, CI/CD, observability and cost control.

## How ETEREO works

A five-phase, evidence-first process: Audit → Architect → Build → Harden → Hand over. Each phase ends in something inspectable — a risk register, decision records, a working release, an evidence pack, and a full ownership hand-over to the client's team.

## Industries

Financial services, healthcare, logistics & mobility, energy & utilities, retail & commerce, and public sector — regulated, operational, high-consequence domains.

## Technology

TypeScript, React / Next.js, Astro; Go, Python, .NET; PostgreSQL, ClickHouse, Kafka; Swift/SwiftUI, Kotlin/Compose, React Native; AWS, Azure, GCP, Kubernetes, Terraform, OpenTelemetry.

## Ways to engage

- **Assessment** — fixed fee, 2–3 weeks: a written read on the system before committing to a programme.
- **Delivery squad** — 3–18 months: a full accountable team shipping in two-week increments.
- **Embedded engineers** — rolling monthly: senior specialists inside existing teams.

## Contact

- Email: hello@etereo.sk
- Location: Bratislava, Slovakia (remote-first, CET)
- Website: ${SITE_URL}/

## O firme (slovensky)

ETEREO (ETEREO s.r.o.) je slovenská softvérová firma so sídlom v Bratislave. Prestavujeme systémy, na ktorých etablované firmy denne bežia: modernizácia starších platforiem, softvér na mieru, SaaS produkty a mobilný aj webový vývoj. Stratégia, architektúra a dodanie pod jednou strechou — jeden tím, ktorý za výsledok ručí. Pracujeme na diaľku, v slovenčine aj angličtine, pre klientov na Slovensku aj v zahraničí.

- Služby: digitálna transformácia a modernizácia systémov, softvér na mieru, SaaS produkty, mobilný vývoj (iOS, Android), webové platformy, cloud a DevOps.
- Odvetvia: financie, zdravotníctvo, logistika, energetika, retail a verejný sektor.
- Kontakt: hello@etereo.sk · Bratislava, Slovensko.

## Notes

- Founded 2026. As a new company, ETEREO does not claim historical project counts or client rosters; case studies shown on the website are labelled illustrative until real client work is published.
`;
writeFileSync(resolve(pub, "llms.txt"), llms);

console.log(`[seo] wrote robots.txt, sitemap.xml, llms.txt for ${SITE_URL}`);
